### ISSUE TITLE
Proposal: remove request/reply and expose just context

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#169]
We always had two objects in the handler callback code, `request` and `reply`.
This because at the beginning of the project, `request` was the request object (as it is today) and `reply` was just a single function to send data back to the user (see https://github.com/fastify/fastify/pull/27).

During the time we created some coupling between the two objects (see the `request` object [inside](https://github.com/fastify/fastify/blob/master/lib/reply.js#L16) `reply`) and add new apis that depends both from `request` and `reply` object is not that easy, see https://github.com/fastify/fastify/issues/146 for example.

Obviously this is a breaking change, the new api will be something like the following:
```js
fastify.decorateContext('util', utility)

fastify.post('/', ctx => {
  ctx.send(ctx.body)
})
```

I think this can be useful and it can be and an investment for the future, enabling a simpler api (we’ll remove `decorateRequest` and `decorateReply` in favor of `decorateContext`) and an easier way to interact between the incoming data and the output generation. Furthermore in the future we can think about optimizing even more the object.

What do you think?

cc @lucamaraschi @davidmarkclements @lmammino @jsumners

**Comment by jsumners** [comment]
I understand what you're saying, but I'm not sure about it. One of the nice things about the current signature is it follows the standard `http` module. But more than that, I think the signature is easier to read/work with:

```
function handler1 (req, res) {
  if (req.headers['x-foo']) return reply.send('foo received')
  reply.send('no foo received') // would like to do `reply('no foo received')`
}

function handler2 (ctx) {
  if (ctx.req.headers['x-foo']) return ctx.res.send('foo received')
  ctx.res.send('no foo received')
}
```

**Comment by delvedor** [comment]
Actually your example should be rewritten like this:
```js
function handler1 (req, reply) {
  if (req.req.headers['x-foo']) return reply.send('foo received')
  reply.send('no foo received')
}

function handler2 (ctx) {
  if (ctx.req.headers['x-foo']) return ctx.send('foo received')
  ctx.send('no foo received')
}
```
Because the actual Fastify request object does not contain the headers of the request.

In this way we can also fix the tricky way to access the plain request object that at the monent is accessible via `request.req`, which is not very handy.
The `ctx` object will have all the methods and properties of the actual `request` and `reply` objects.

Following a more complex example:
```js
fastify.decorateContext('handleHeaders', () => {
  var header = this.req.headers['key']
  // do something
  return this
})

fastify.post('/example', ctx => {
  ctx.handleHeaders()
  var user = ctx.body.user
  ctx.type('text/plain').send(`Hello ${user}`)
})
```

**Comment by allevo** [comment]
It's seem that only [koajs](http://koajs.com/) implements an api like that.

Are `ctx.req` and `ctx.req` instance of [IncomingMessage](https://nodejs.org/docs/latest/api/http.html#http_class_http_incomingmessage) and [ServerResponse](https://nodejs.org/docs/latest/api/http.html#http_class_http_serverresponse)?

**Comment by jsumners** [comment]
Familiarity is definitely a big selling point to newcomers.

**Comment by davidmarkclements** [comment]
Personally, I very much like the single `ctx`, also destructuring:

```js
function handler2 ({req, send}) {
  if (req.headers['x-foo']) return send('foo received')
  send('no foo received')
}
```

However, I remember having a discussion early on with @mcollina around this, 
he was particularly interested in req, reply (with reply as a function) to keep 
tap familiarity with Hapi API

In either case we have a lot of chances here with the current API to be *like*
but not *the same as* Express and Hapi - this would also add Koa to the mix. 

The problem there is you may signal one type of behaviour using a familiar API
that then acts in unexpected ways. But this is already a recognized trade-off
for the adoption aspect.

Could this be implemented as a separate abstraction that plugs in to fastify,
so you can opt into the `ctx` approach - which is nice for koa users.. plus koa
users are used to hand assembling all the pieces

**Comment by allevo** [comment]
> Familiarity is definitely a big selling point to newcomers.

Yes, but performance and maintainability is more important IMHO.

I am not against it but we should have a list of the impacts

**Comment by lmammino** [comment]
I am not very familiar with the internals of fastify, so I can only bring an opinion based on the API aesthetic.

Anyway, I am currently working on a [little web framework for AWS Lambda](https://github.com/Plnt9/middy) and in this project we took a very similar decision from the get go.

We decided to have the following signature in every middleware function:

```javascript
function (handler, next) {}
```

Where `handler` is an object that has references to `event` (a request in Lambda land), `response` and `error`.

This is just to say that I really like this approach and mainly for the following reasons:

  - Function signature gets very streamlined
  - It's easy to use destructuring to get only the pieces you need (as already pointed out by @davidmarkclements )
  - It's easy to extend the context in the future without causing breaking changes if needed

With that being said, I agree also with @allevo: since the project has already a good traction, this decision isn't a light one and it would be good to do a proper analysis of the change impact before discussing it further.

**Comment by delvedor** [comment]
@allevo 
> It's seem that only koajs implements an api like that.

Yeah, [merry](https://github.com/shipharbor/merry) as well, but in a slightly different way.

> Are ctx.req and ctx.req instance of IncomingMessage and ServerResponse?

Yep

@jsumners 
> Familiarity is definitely a big selling point to newcomers.

That's true, we should decide which one has more "weight", familiarity, or maintainability and easiness? (don't forget that this change will completely solve probpems like the one @allevo encountered when building [fastify-accepts](https://github.com/fastify/fastify-accepts) or in  https://github.com/fastify/fastify/issues/146.

@davidmarkclements 
> Could this be implemented as a separate abstraction that plugs in to fastify,
so you can opt into the ctx approach - which is nice for koa users.. plus koa
users are used to hand assembling all the pieces

Personally if we want to do this I'd like to see it in core, because it will also give us more elasticity, same for plugin builders.

___

We should decide if we want to pay the cost of a familiar api, but we must  also keep in mind that Fastify introduces a completely different way to handle encapsulation and namaspacing with plugins, the familiar api thing is very small.

Lastly, if we want to do a change of this size, the best moment is now, we are still in beta and we have not a big community, so we can talk together and decide if it is worth breaking everything.

ps regarding the mix of different apis, express/hapi/koa, it's an interesting discussion. Familiarity is a selling point but try to do something new is also important, and *maybe* valued.

**Comment by delvedor** [comment]
Obviously we can think about change some function signature in the api, for example `.send` could become `.reply`:
```js
fastify.get('/example', ctx => {
  ctx.reply({ hello: 'world' })
})
```

What I mean is, if we want to do a change of this size, we can think about update some api that during the time became odd.

**Comment by mcollina** [comment]
I am kind of 👎  (and my opinion took some time to mature) to this proposal for two reasons:

1. we are encouraging to keep a reference to `ctx`. Very likely, this holds a reference to the parsed body. This reference prevents the body to be collected, if it is not needed elsewhere. Currently this is not happening (but please check).

2. There is a number of attached method to `Reply` (see https://github.com/fastify/fastify/blob/master/lib/reply.js#L109-L145), which are specific to replying.
Should we renamed them? We are effectively removing a namespace, so it might also cause problems with plugins.

3. It looks like to be less familiar.

On the 👍  side we have:

1. it simplifies the plugin API.

2. It fits better with the HTTP2 "core" API, where there is just one `HTTP2Stream` https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_class_http2stream.

3. destructuring

I'm torn.

@coopnd @eljefedelrodeodeljefe what do you think?

**Comment by eljefedelrodeodeljefe** [comment]
I think Koa proves that adoption is kinda hard when you have too different APIs. Similarly `lambda` doesn't serve as good example, because (1) lamdba feels very awkward, feels almost like a god object, but least makes normal Node.js practices incompatible, (2) and also you can see the other 50% of the cloud functions providers use `req`.

I learned to be conservative on things like that and am strongly 👎  on `ctx`. UX is king for everything. Node-core-like `req` is much more battle tested and familiar. More familiar UX is better UX.

Thanks for asking @mcollina

**Comment by mcollina** [comment]
Thanks for your opinion @eljefedelrodeodeljefe!

**Comment by delvedor** [comment]
I had a conversation with @mcollina, following the idea we come up with:
> we are encouraging to keep a reference to ctx. Very likely, this holds a reference to the parsed body. This reference prevents the body to be collected, if it is not needed elsewhere. Currently this is not happening (but please check).

Here the issue is that objects like `body`, `query`, `req`and `params`, will remain in context until `send`has been called. This can drive to an higher memory usage in high stressed contexts, but it can be easily solved by cleaning manually the references, `ctx.body = null` for example.
@mcollina came up with a proposal to add an api `clearRef()` that does exactly this thing, which could fit in a nice plugin. We'll document this behaviour and the user will decide how to act. 
___
> There is a number of attached method to Reply (see https://github.com/fastify/fastify/blob/master/lib/reply.js#L109-L145), which are specific to replying.
Should we renamed them? We are effectively removing a namespace, so it might also cause problems with plugins.

Yes, we are basically merging the actual `request` and `reply` objects, so all the plugins that use them must be updated.

> It fits better with the HTTP2 "core" API, where there is just one HTTP2Stream https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_class_http2stream.

This is a very nice point.

@eljefedelrodeodeljefe thank you! :)

**Comment by mcollina** [comment]
I'm still not convinced this is a good idea BTW, and it will be a shaping moment for the project.
Let's take some time before coming up to a decision.

**Comment by delvedor** [comment]
Agree, it's a big change and we should think carefully about it.

I'll update the first comment with a pros cons list :)

**Comment by eljefedelrodeodeljefe** [comment]
Agree, take your time. Btw frankly and am not intending to push this in any direction or be rude here, but I would very likely refactor my projects back to `express` in the `ctx` case. Would be a loss tho.

**Comment by jsumners** [comment]
> During the time we created some coupling between the two objects (see the `request` object inside `reply`)...

Correct me if I'm wrong, but isn't the `request` object here the raw non-Fastify request object from core? It seems to me this reference would only be a problem if it were the Fastify specific request object.

**Comment by mcollina** [comment]
> Correct me if I'm wrong, but isn't the request object here the raw non-Fastify request object from core? It seems to me this reference would only be a problem if it were the Fastify specific request object.

Request and Reply are custom to fastify: 
https://github.com/fastify/fastify/blob/master/docs/Request.md
https://github.com/fastify/fastify/blob/master/docs/Reply.md

**Comment by jsumners** [comment]
@mcollina yes, the `request` and `reply` passed into a handler are the Fastify wrapped objects. But the `request` attached internally to the Fastify `reply` is the original `http.request`:

1. https://github.com/fastify/fastify/blob/master/fastify.js#L130
2. https://github.com/fastify/fastify/blob/master/fastify.js#L177
3. https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L14
4. https://github.com/fastify/fastify/blob/master/lib/reply.js#L16

**Comment by coopnd** [comment]
IMO with the excitement around serverless and functional programming this is a step in the right direction.  KISS for the win.  

In light of plugins, a simple destructing, as mentioned by @mcollina,  could take a lot pain from refactoring if `ctx` is shaped the way I'm imagining it right now...or even aliases on the object to ease the transition...I don't think it will be as terrifying as it sounds...

**Comment by allevo** [comment]
> IMO with the excitement around serverless and functional programming this is a step in the right direction. 

Good point

> @mcollina came up with a proposal to add an api clearRef() that does exactly this thing, which could fit in a nice plugin. We'll document this behaviour and the user will decide how to act.

I'm :-1::  in the plugin chain this could be evil breaking the encapsulation.

For the `context`: I'm not convinced that this is a good thing. This is a breaking change and it should be followed by some improvement as justification (and not only UX improvement if there're any)

Which performance improvement will we have using `ctx` instead of `req` and `res` (without using `clearRef`)?

**Comment by delvedor** [comment]
I've added a pros/cons list, fell free to suggest other points.

As you can see there are a lot of pros, but the *unfamiliar api* cons is is rather heavy.

**Comment by jsumners** [comment]
> Remove odd apis, such as request.req to access the raw request object

Simply alias it to `request.raw`.

**Comment by allevo** [comment]
**cons**: The garbage collector will wait the response ends

**Comment by delvedor** [comment]
@allevo it should not influence the performance so much, and if you need that kind of optimization checkout this [comment](https://github.com/fastify/fastify/issues/169#issuecomment-324297441) :)

**Comment by mcollina** [comment]
I propose we close this. This ship as sailed and we cannot change such a fundamental API while we are trying to build an ecosystem.

**Comment by jsumners** [comment]
> I propose we close this. This ship as sailed and we cannot change such a fundamental API while we are trying to build an ecosystem.

I agree.

**Comment by delvedor** [comment]
> I propose we close this. This ship as sailed and we cannot change such a fundamental API while we are trying to build an ecosystem.

Agree, in the future we should figure out a way to make a better interaction between `req` and `reply`.

Thanks everyone for contributing!
