### ISSUE TITLE
inject() returns undefined if called before ready()

### ISSUE THREAD

**Issue by m-ronchi** [fastify/fastify#2344]
## 🐛 Bug Report

fastify.inject() returns undefined if called before ready, causing subsequent chai to fail with unhelpful error

## To Reproduce

```js
const server = fastify();

await server.inject().get("...").end();
```

## Expected behavior

inject() returns a valid object even if called before ready().
if it is not possible, throw an error explaining that ready() must be called first

## Your Environment

- *node version*: 12
- *fastify version*: >=2.15
- *os*: Mac

**Comment by Eomm** [comment]
The issue happens for the chaining usage

```
const fastify = require('./fastify')()

;(async function () {
  fastify.get('/', async () => 'hello')
  const res = await fastify.inject().get('/').end()
  console.log(res.payload)
})()
```


As a workaround, till a fix, the usage of the options works

```
const res = await fastify.inject('/')
```

**Comment by mcollina** [comment]
I think this should be fixed on master.

**Comment by zhangwinning** [comment]
> The issue happens for the chaining usage
> 
> ```
> const fastify = require('./fastify')()
> 
> ;(async function () {
>   fastify.get('/', async () => 'hello')
>   const res = await fastify.inject().get('/').end()
>   console.log(res.payload)
> })()
> ```
> 
> As a workaround, till a fix, the usage of the options works
> 
> ```
> const res = await fastify.inject('/')
> ```

hi @Eomm, I run above this example, it's no problem, the question have solved ?

**Comment by Eomm** [comment]
I didn't work on it: it could be useful if someone could send a PR with a test to avoid regression 👍

**Comment by zhangwinning** [comment]
@Eomm, the pr  https://github.com/fastify/fastify/pull/2257 solve it, and the test unit add too.

**Comment by Eomm** [comment]
Yeah, but this issue is referring to Fastify v2, that one was on v3

The issue is still here https://runkit.com/embed/lj0xf1catkj1 😞

**Comment by zhangwinning** [comment]
Hey @Eomm, thanks for the answer. it's seems not a problem, while I don't  know how to modify it, I should modify specific 

v2 version?  if I only modify 2.15.2 version code, 2.15.1 may have errors. so please give me guide, if I know it. I'd like to work on this.

**Comment by Eomm** [comment]
You need to fork this repo and checkout the "v2.x" branch.
Then do the changes to the code with tests and push the code.
At the end you can open a pr from your fork project to this one to merge your changes.

I think the pr you linked could be a good inspiration to apply the changes to v2 too 👍🏼

**Comment by zhangwinning** [comment]
Good to know, thanks! I will solve it this tonight

**Comment by zekth** [comment]
Seems like this issue can be closed now?
