### ISSUE TITLE
Feature request: make payload for 4xx and 5xx responses configurable

### ISSUE THREAD

**Issue by paolochiodi** [fastify/fastify#360]
Would be useful to customise the payload in the response for the default "error" response for any status code returned by fastify.

In my situation, I'd like to respond with something like `{code, message}` instead of `{error, message, statusCode}`

If I understand correctly one can use:
- `fastify.setErrorHandler(handler(error, reply))` (as implicitly proposed in this issue #341) but that is bypassed by non-application error (again see #341 - the same applies to other errors such as 415)
- `fastify.setNotFoundHandler(handler(request, reply))` but that covers only 404s. 

Would be great to have one unified way to customise those responses.

**Comment by allevo** [comment]
Have you tried to setup a custom serializer ?
https://github.com/fastify/fastify/blob/master/docs/Validation-And-Serialize.md#serialize

**Comment by paolochiodi** [comment]
Interesting, thank you for the insight.
I may use combination of the serialiser to strip out the property I don't need and `fastify.extendServerError` to add the ones I need (are those invoked by internal fastify errors as well?)

To be honest though, it sounds a bit confusing and an explicit way would be easier to understand

**Comment by jsumners** [comment]
> To be honest though, it sounds a bit confusing and an explicit way would be easier to understand

I agree.

**Comment by allevo** [comment]
Sorry, I gave you a wrong information.
Actually the current `fastify` implementation handles the error (not the boom error) in this way:
https://github.com/fastify/fastify/blob/master/lib/reply.js#L57
[Here](https://github.com/fastify/fastify/blob/master/lib/reply.js#L158) the `errorHandler` is used to serialize the error and write the response directly.

Have you tried it?

**Comment by paolochiodi** [comment]
Yes, I did.
I set up the error handler with `fastify.setErrorHandler`, but the error handler is not called for fastify internal "errors" which include status codes 400 (for validations), 404, 415 etc. 
On this topic see also #341

**Comment by delvedor** [comment]
This should be addressed in https://github.com/fastify/fastify/pull/330.
Can you try with [this](https://github.com/letzdoit/fastify/tree/onSend) branch?

**Comment by delvedor** [comment]
This should be addressed in the latest release, can you try it?

**Comment by paolochiodi** [comment]
Hi, thanks for the update. I'll be able to test it in the weekend

**Comment by paolochiodi** [comment]
Tested latest release and can confirm that `setErrorHandler` is called for internal 4xx errors (I've tested 400 and 404).

This solves my problem, so for me it's ok to close the issue.
However, I'd suggest to better define the meaning and the behaviour of `setErrorHandler` (i.e. customising core 4xx error vs intercepting and wrapping application errors)

**Comment by delvedor** [comment]
@paolochiodi thank you for trying! :)
Regarding the documentation I agree.

**Comment by gendronb** [comment]
@paolochiodi @delvedor 

I'm reading all this before opening a new issue, but I still cannot figure out how to setup a custom error serializer.

My use case is similar to yours (removing the statusCode property), but I also want to add a new `errorCode` property (ideally, I'd like to add my own `code` property). But looking at the source, anything added seems to get swallowed by the default serializer : 

https://github.com/fastify/fastify/blob/5de74406dbff5cba90516f6c9f499ea9d5e70e1b/lib/reply.js#L27

I'm using version 2.1.0

**Comment by mcollina** [comment]
@gendronb feel free to open a new issue on https://github.com/fastify/help.
