### ISSUE TITLE
[Bug] Custom thrown 404 error not showing on prefixed routes

### ISSUE THREAD

**Issue by edsamonte** [fastify/fastify#844]
I'm using a Service Layer design pattern for my app and would want to decouple my controller and the services. I have this particular piece of code:
```js
// services/app.js
const httpErrors = require('http-errors');
async function create(data) {

  let app = await apps.findById(data.appId);
  if (!app) {
    throw new httpErrors.NotFound('App not found');
  }
  return {};
}

// controllers/apps.js
fastify.post('/apps', async function(request, reply) {
  return await appService.create(request.body);
});
```

And I've set an ErrorHandler and NotFoundHandler for my app. Unfortunately, I keep getting:
```
Trying to send a NotFound error inside a 404 handler. Sending basic 404 response.
```

I'm building a REST API backend and would like to add context to my 404 errors (i.e. App not found, Device not found, User not found, etc.). Putting the 404 return would defeat the purpose of de-coupling the service layer as I would want the controller to receive only the result and any error encountered would be handled by the ErrorHandler. 

Any workaround for this? Or might as well, is there a reason why it is not supported (or rather [filtered](https://github.com/fastify/fastify/blob/bb2c1bc03f8b99bb0b844993dba93aa853d97701/lib/reply.js#L254)) in the first place?

#### Context
* *node version*: 8.10.0
* *fastify version*: ^1.1.0
* *os*: Mac

**Comment by nwoltman** [comment]
This seems like a bug. @edsamonte would you be able to provide a minimal test case that reproduces this issue? Right now this is working as expected with a very simple case:

```js
const httpErrors = require('http-errors')
const fastify = require('fastify')();

fastify.get('/', async (request, reply) => {
  throw new httpErrors.NotFound();
});

fastify.setNotFoundHandler((request, reply) => {
  reply.send('Custom 404');
});

fastify.inject('/', (err, res) => {
  if (err) throw err;
  console.log(res.payload); // Logs 'Custom 404'
});
```

Also, make sure that your not-found handler isn't throwing a `NotFound` error. Doing that is supposed to trigger the warning you're getting because a custom not-found handler isn't allowed to call itself by throwing an error.

**Comment by edsamonte** [comment]
Looks like a bug with the `prefix` option of the `fastify.register`. 

Error occurs:
```js
const httpErrors = require('http-errors');
const fastify = require('fastify')({
  // ignoreTrailingSlash: true,
  logger: {
    level: 'debug',
  },
});


fastify.register(async function(fastify, opts) {
  fastify.get('/test', async function() {
    throw new httpErrors.NotFound();
  })
},{prefix: '/v1'});

fastify.inject('/v1/test', (err, res) => {
  if (err) throw err;
  console.log(res.payload); // Logs 'Custom 404'
});

```

Error does *not* occur:
```js
const httpErrors = require('http-errors');
const fastify = require('fastify')({
  // ignoreTrailingSlash: true,
  logger: {
    level: 'debug',
  },
});


fastify.register(async function(fastify, opts) {
  fastify.get('/v1/test', async function() {
    throw new httpErrors.NotFound();
  })
});

fastify.inject('/v1/test', (err, res) => {
  if (err) throw err;
  console.log(res.payload); // Logs 'Custom 404'
});
```

**Comment by nwoltman** [comment]
@edsamonte This should be fixed with `fastify@1.1.1`. Could you see if the problem still happens with that version?

**Comment by edsamonte** [comment]
Confirming that the issue has been fixed with `fastify@1.1.1`. Thanks, @nwoltman.

**Comment by nwoltman** [comment]
> Currently, the not-found handler does not have access to the actual error.

@edsamonte This is a very interesting point. Automatically routing 404 errors to the not-found handler may not be the best thing to do. I'm going to open a separate issue to start a discussion about this.

**Comment by bacloud22** [comment]
I am facing the same error with the exact code in documentation:

```js
  app.register(function (instance, options, done) {
    instance.setNotFoundHandler(function (request, reply) {
      // Handle not found request to URLs that begin with '/v1'
      reply.status(404).send({ error: 'Resource not found. Please check API documentation' })
    })
    done()
  }, { prefix: '/api' })
```

It does send a 404 error, but the default one. I also tried to put this prior or after I register routes, or any other plugin but with no results. To confirm this is a bug still, removing the `prefix` option, it catches well 404 errors but then on all routes.

Thanks

**Comment by mcollina** [comment]
The whole error handling logic has been completely refactored since this issue was open. Please open a fresh one.
